<img class="alignright  wp-image-3284" title="poster-mini" src="/img/pages/poster-mini-771x1024.png" alt="" width="370" height="491"></p>

<p>A Educação Proibida é um documentário produzido no ano de 2012, que questiona a escolarização moderna e propõem um novo modelo educativo. O filme tem como objetivo dar visibilidade a experiências no âmbito educacional, que contrapõem ao modelo pedagógico tradicional.</p>
<p>O documentário é um projeto realizado por jovens que partiram do ponto de vista de quem aprende e resolveram embarcar numa investigação que abrange 8 países, entrevistando mais de 90 educadores com perspetivas alternativas educacionais. O filme foi financiado conjuntamente por centenas de co-produtores e tem licenças livres que permitem incentivar a cópia e reprodução.</p>
<p>A Educação Proibida pretende refletir, alimentar e promover o debate social sobre os fundamentos que sustentam a escola, promover o desenvolvimento de uma educação integral centrada no amor, respeito, liberdade e aprendizagem.</p>  

<div id="quienes1">
  <h3>Sinopse</h3>
    <p>O modelo atual de escola, já existe a mais de 200 anos e ainda é considerado a principal forma de acesso à educação. Hoje, escola e educação são conceitos  amplamente discutidos em fóruns acadêmicos, políticas públicas, instituições educativas, meios de comunicação e espaços da sociedade civil. Desde sua origem, a escola tem sido caracterizada por estruturas e práticas que hoje são consideradas obsoletas e ultrapassadas, que não acompanham as necessidades do século XXI.Sua principal falha está em um projeto que não leva em consideração a natureza da aprendizagem, a liberdade de escolha ou a importância do amor e relações humanas no desenvolvimento individual e coletivo.</p>
    <p>A partir dessas reflexões críticas surgiram ao longo dos anos, novas propostas de educação, pondo em prática formas de pensar diferentes. "A Educação Proibida" é um documentário que procura recuperar muitas dessas propostas, explorar as idéias e experiências daqueles que ousaram mudar a estrutura do modelo educativo da escola tradicional.</p>
    <p>Mais de 90 entrevistas com educadores, acadêmicos, profissionais, autores, mães e pais; uma turnê de oito países da América Latina através de 45 experiências educativas não convencionais; mais de 25.000 seguidores nas redes sociais antes de seu lançamento e um total de 704 co-produtores que participaram no seu financiamento coletivo convertido para "A Educação Proibida" em um fenômeno único. </p>
</div>
