<img class="alignright  wp-image-3284" title="poster-mini" src="/img/pages/poster-mini-771x1024.png" alt="" width="370" height="491"></p>

<p>A Educação Proibida é um documentário produzido no ano de 2012, que questiona a escolarização moderna e propõem um novo modelo educativo. O filme tem como objetivo dar visibilidade a experiências no âmbito educacional, que contrapõem ao modelo pedagógico tradicional.</p>
<p>O documentário é um projeto realizado por jovens que partiram do ponto de vista de quem aprende e resolveram embarcar numa investigação que abrange 8 países, entrevistando mais de 90 educadores com perspetivas alternativas educacionais. O filme foi financiado conjuntamente por centenas de co-produtores e tem licenças livres que permitem incentivar a cópia e reprodução.</p>
<p>A Educação Proibida pretende refletir, alimentar e promover o debate social sobre os fundamentos que sustentam a escola, promover o desenvolvimento de uma educação integral centrada no amor, respeito, liberdade e aprendizagem.</p>  

<div id="quienes1">
  <h3>Sinopsis</h3>
    <p>La escuela ha cumplido ya más de 200 años de existencia y es aun considerada la principal forma de acceso a la educación. Hoy en día, la escuela y la educación son conceptos ampliamente discutidos en foros académicos, políticas públicas, instituciones educativas, medios de comunicación y espacios de la sociedad civil.Desde su origen, la institución escolar ha estado caracterizada por estructuras y prácticas que hoy se consideran mayormente obsoletas y anacrónicas. Decimos que no acompañan las necesidades del Siglo XXI. Su principal falencia se encuentra en un diseño que no considera la naturaleza del aprendizaje, la libertad de elección o la importancia que tienen el amor y los vínculos humanos en el desarrollo individual y colectivo.</p>
    <p>A partir de estas reflexiones críticas han surgido, a lo largo de los años, propuestas y prácticas que pensaron y piensan la educación de una forma diferente. “La Educación Prohibida” es una película documental que propone recuperar muchas de ellas, explorar sus ideas y visibilizar aquellas experiencias que se han atrevido a cambiar las estructuras del modelo educativo de la escuela tradicional.</p>
    <p>Más de 90 entrevistas a educadores, académicos, profesionales, autores, madres y padres; un recorrido por 8 países de Iberoamérica pasando por 45 experiencias educativas no convencionales; más de 25.000 seguidores en las redes sociales antes de su estreno y un total de 704 coproductores que participaron en su financiación colectiva, convirtieron a “La Educación Prohibida” en un fenómeno único. Un proyecto totalmente independiente de una magnitud inédita, que da cuenta de la necesidad latente del crecimiento y surgimiento de nuevas formas de educación.</p>
</div>
