<p>La Educación Prohibida es una película documental que se propone cuestionar las lógicas de la escolarización moderna y la forma de entender la educación, visibilizando experiencias educativas diferentes, no convencionales que plantean la necesidad de un nuevo paradigma educativo.</p>
<p>La Educación Prohibida es un proyecto realizado por jóvenes que partieron desde la visión del quienes aprenden y se embarcaron en una <a href="/investigacion.php">investigación </a>que cubre 8 países realizando entrevistas a más de <a href="/entrevistados.php">90 educadores</a> de propuestas educativas alternativas. La película fue financiada <a href="/realizacion/financiacion-colectiva/">colectivamente </a>gracias a cientos de <a href="/realizacion/financiacion-colectiva/coproductores/">coproductores </a>y tiene <a href="/distribucion/">licencias libres </a>que permiten y alientan su copia y reproducción.</p>
<p>La Educación Prohibida se propone alimentar y disparar un debate reflexión social acerca de las bases que sostienen la escuela, promoviendo el desarrollo de una educación integral centrada en el amor, el respeto, la libertad y el aprendizaje.<br>
<img class="alignright  wp-image-3284" title="poster-mini" src="/img/pages/poster-mini-771x1024.png" alt="" width="370" height="491"></p>
<div id="quienes1">
<h3>Sinopsis</h3>
  <p>La escuela ha cumplido ya más de 200 años de existencia y es aun considerada la principal forma de acceso a la educación. Hoy en día, la escuela y la educación son conceptos ampliamente discutidos en foros académicos, políticas públicas, instituciones educativas, medios de comunicación y espacios de la sociedad civil.Desde su origen, la institución escolar ha estado caracterizada por estructuras y prácticas que hoy se consideran mayormente obsoletas y anacrónicas. Decimos que no acompañan las necesidades del Siglo XXI. Su principal falencia se encuentra en un diseño que no considera la naturaleza del aprendizaje, la libertad de elección o la importancia que tienen el amor y los vínculos humanos en el desarrollo individual y colectivo.</p>
  <p>A partir de estas reflexiones críticas han surgido, a lo largo de los años, propuestas y prácticas que pensaron y piensan la educación de una forma diferente. “La Educación Prohibida” es una película documental que propone recuperar muchas de ellas, explorar sus ideas y visibilizar aquellas experiencias que se han atrevido a cambiar las estructuras del modelo educativo de la escuela tradicional.</p>
  <p>Más de 90 entrevistas a educadores, académicos, profesionales, autores, madres y padres; un recorrido por 8 países de Iberoamérica pasando por 45 experiencias educativas no convencionales; más de 25.000 seguidores en las redes sociales antes de su estreno y un total de 704 coproductores que participaron en su financiación colectiva, convirtieron a “La Educación Prohibida” en un fenómeno único. Un proyecto totalmente independiente de una magnitud inédita, que da cuenta de la necesidad latente del crecimiento y surgimiento de nuevas formas de educación.</p>
</div>
